-- Separate virtual warehouses so dashboards never starve nightly loads.
CREATE WAREHOUSE IF NOT EXISTS WH_OPS         WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS WH_REPORTING   WITH WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS WH_INGEST      WITH WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE DATABASE IF NOT EXISTS HMIS;
CREATE SCHEMA   IF NOT EXISTS HMIS.GOLD;

CREATE ROLE IF NOT EXISTS R_HMIS_ANALYST;
CREATE ROLE IF NOT EXISTS R_HMIS_CASEWORKER;
CREATE ROLE IF NOT EXISTS R_HMIS_HUD_REPORTING;
